### ISSUE TITLE
Deploy 2.3 to pypi

### ISSUE THREAD

**Issue by yourcelf** [ubernostrum/django-registration#109]
Looks like v2.3 is ready in the source tree (89812bcde9d1e4875d5ce7dc737b4b176da98884) but the latest release on pypi is still 2.2.  Would be nice if you could publish 2.3 to pypi so we can install that without resorting to a git URL.

**Comment by justinmayer** [comment]
I agree that it would be nice to have a new release published to PyPI. That said, I'd like to see #106 resolved first. 😅

**Comment by ubernostrum** [comment]
The fact that I've started fiddling with the packaging files and version numbers is not an indication that a new version is released. The indication that a new version is released is when that version is on PyPI and a signed tag for the version number is present in the repository.

**Comment by ubernostrum** [comment]
Another test.

**Comment by justinmayer** [comment]
@ubernostrum: [As I opined a few months ago](https://twitter.com/jmayer/status/872141953714061312), it would be great to have an issue open for the next release, and then only close it once the next release is out. That way, users can subscribe to the issue in order to be notified when the new release is up on PyPI. Otherwise, it's hard for folks to know when a new release is available.

To that end, would you consider re-naming this issue to "Release version 2.3" and then re-opening this issue?

**Comment by henrinie** [comment]
Is there a new release of 2.3, it seems to be in pypi? Where can I find the change log?
