### ISSUE TITLE
Ability to resend activation email on HMAC backend

### ISSUE THREAD

**Issue by jmfederico** [ubernostrum/django-registration#112]
When using the HMAC backend, activation emails are only sent once when the user is created, but if the user needs to get a new activation email, there is no way for the user to request it.

It would be great if the user was able to request a new activation email.

**Comment by ubernostrum** [comment]
Unlike the model-based workflow, django-registration can't easily put a "re-send email" button in the admin for the HMAC workflow, because the HMAC workflow has no models -- it would have to figure out what admin class is used for the user model, then monkeypatch a re-send action into that admin class, which is not something I really want to do.

**Comment by jmfederico** [comment]
I wasn’t clear with what my idea.

What I think would be helpful is to have the user be able to request another activation email. So have a “forgot password” kind of link, but with “re-send activation email” in the login page.
