### ISSUE TITLE
2.x branch compatibility with Django 2.0

### ISSUE THREAD

**Issue by w00kie** [ubernostrum/django-registration#134]
Hello,

Is there a plan to make the 2.x branch compatible with Django 2.0 sometime soon? I'm starting a project right now and would like to use django-registration but would rather not be stuck on Django 1.11 if possible.

Thanks,
Francois

**Comment by ubernostrum** [comment]
The 2.x branch will never be compatible with Django 2.0. The `master` branch already is, and will be the basis of the 3.x series of django-registration.

**Comment by jmfederico** [comment]
Ma I ask why?

Version 2.4.0 seems to work fine with Django 2.

**Comment by ubernostrum** [comment]
Leaving the explanation here for reference: the problem is the auth URLs, which django-registration 2.x tries to automatically `include()` for you. They've changed in backwards-incompatible ways (function-based to class-based, and changed their default names in Django's provided URLconf), and trying to pile yet another compatibility hack into django-registration 2.x is not something I plan to do. So django-registration 2.x won't ever officially support Django 2.0+.

**Comment by amorino** [comment]
Is there any ETA on the 3.0? Installing django-registration uninstall django 2.* and installs django 1.11 which is a little problematic.

**Comment by jmfederico** [comment]
@amorino use version 2.4.0, that one works with Django 2.
