### ISSUE TITLE
Rename base views

### ISSUE THREAD

**Issue by unho** [ubernostrum/django-registration#178]
I've just spotted these imports:

```python
from django_registration.views import ActivationView as BaseActivationView
from django_registration.views import RegistrationView as BaseRegistrationView
```
Then I checked those base views' code and it turns out that they are coded to be base view classes, so I am wondering if they should be renamed to `BaseRegistrationView` and `BaseActivationView`. That way it would be clear that you can't just use those views, but that are meant to be subclassed. And as a bonus it will lead to cleaner imports:

```python
from django_registration.views import (BaseActivationView,
                                       BaseRegistrationView)
```

**Comment by ubernostrum** [comment]
They already will tell you that you have to subclass, because the key methods on them raise `NotImplementedError`. But I don't think I'd make this change, because there's no requirement to have subclasses use exactly the names `RegistrationView` and `ActivationView`; the import statements are that way because I chose to have the subclasses in the built-in backends use those names.
