### ISSUE TITLE
Use custom User model

### ISSUE THREAD

**Issue by fronbasal** [ubernostrum/django-registration#195]
`RegistrationForm(UserCreationForm)` should substitute `RegistrationForm.Meta.model` with `get_user_model`. This prevents the need of a custom `RegistrationForm`.

**Comment by ubernostrum** [comment]
This is not a bug in django-registration. This is absolutely deliberate and intended behavior. You are *supposed* to be forced to write your own registration form.

django-registration does this because it is not safe to deploy your code until you have read [the documentation on using custom user models in django-registration](https://django-registration.readthedocs.io/en/3.0.1/custom-user.html) and ensured compatibility between your user model and the form you're using for registration. So django-registration will deliberately and by design crash if you just try to deploy with a custom user model, but without doing that work. Once you've done the work, you swap in a form that's pointed at the correct model and deploy. This also makes clear that compatibility with your custom user model is your responsibility, not django-registration's, and that django-registration does not have to try to magically work by default with every conceivable thing people might do in their user model.

Also, ten seconds' worth of looking through previously-filed issues in this repository would have explained all this to you.
