### ISSUE TITLE
Still Getting the SIX import error

### ISSUE THREAD

**Issue by pymike00** [ubernostrum/django-registration#199]
Hello,

I am still getting the same issue discussed in this pull request regarding SIX (https://github.com/ubernostrum/django-registration/pull/192) with the new version 3.0.1.

I can see that the line importing six has been removed from your repo here (https://github.com/ubernostrum/django-registration/blob/master/src/django_registration/validators.py) but when I do pip install django-registration I still have the "from django.utils import six" line in validators.py.

Django 3.0.2
django-registration 3.0.1
pip 19.2.3

Python 3.8.1, Linux Manjaro

**Comment by TomasLoow** [comment]
But django-registration 3.0.1 was released in May 2019 though. The realease including the six-fix has not been made yet.

**Comment by GiuseppeCoretti** [comment]
Hello,

I solved the problem by replacing into file validation.py 

`from django.utils import six`

with

`import six`

**Comment by ubernostrum** [comment]
As has already been pointed out, and as you would have seen if you had looked at the history in the issue tracker, the next packaged release will be compatible with Django 3.0. The last packaged release was not. The documentation and trove classifiers for the last packaged release made this clear, and declared exactly which versions of Django were supported; Django 3.0 was not one of those versions (because Django 3.0 had not been released at that time!).

Also, every time someone files a duplicate issue for something that has already been answered, it takes away from the limited time available to work on getting the next release finished and packaged. **PLEASE** in the future look at the history in the issue tracker before you file a new issue.
