### ISSUE TITLE
``RegistrationView`` only supports ``ModelForm`` but not conventional forms

### ISSUE THREAD

**Issue by throwable-one** [ubernostrum/django-registration#228]
``RegistrationView#get_form:73``
```
        form_model = form_class._meta.model
```
It doesn't work with betterforms ``MultiModelForm`` or any other form that isn't ``ModelForm``.

What about checking ``_meta`` field and ignoring result if it doesn't exist?

**Comment by ubernostrum** [comment]
This is a much larger and more complex feature request than I think you're aware of, because what you're really heading down the path of doing is "what if I have a bunch of account-related model instances to create in a complex possibly-multi-step form wizard". Which would require some major code changes in django-registration to try to support. For now, it operates on the assumption that signing up a user involves one form, tied to one model, and that any additional forms or things you want to process or create afterward will be done in your own code.
