### ISSUE TITLE
Is it by design or bug that Activation Form doesn't show "already activated" errors?

### ISSUE THREAD

**Issue by maklabu** [ubernostrum/django-registration#249]
In 5.1 the activation form, the new one to force a POST request, doesn't show any error messages like "already activated" . Only the view afterwards.
Is it by design or is this a bug (probably in my implementation).

**Comment by ubernostrum** [comment]
You'll want to read [the template documentation](https://django-registration.readthedocs.io/en/stable/quickstart.html#django-registration-activation-form-html).

Basically: the form will have errors only if the activation key is missing or fails cryptographic verification. If the key passes verification, the form is valid, but the activation still might fail (such as an already-activated user). In that case, the context variable `activation_error` has information about what failed.

It's done this way deliberately because there's pretty much always going to be a need for some way to do complex logic with the validated form data and that might fail, so the activation flow anticipates that and has support for both "normal" data-validation errors on the form and also other activation failures which occur while trying to use validated data from the form.
