### ISSUE TITLE
Unable to register user with custom User model

### ISSUE THREAD

**Issue by andreyrusanov** [ubernostrum/django-registration#69]
RegistrationForm is inherited from UserCreationForm and uses model declaration from it's Meta.

The problem is that user model in UserCreationForm defined in a wrong way, not with get_user_model(), but imported directly from django.contrib.auth.models. It causes a bug during registration if User model is custom.

**Comment by ubernostrum** [comment]
[The documentation already explains this and what to do](https://django-registration.readthedocs.io/en/2.2/custom-user.html). At this time I don't plan to have django-registration try to change the model the form points at.

**Comment by ubernostrum** [comment]
And since I imagine this will come up again at some future time, the full explanation so I can cite it:

The problem here is that custom users break a lot of things, and before using django-registration with a custom user there's a rundown of stuff people need to check about their user model and integration they need to do to ensure django-registration works with it. Allowing it to "work" -- in the sense that it doesn't immediately error at the form level -- without doing this is a risk, since it leads people into thinking they're in the clear when really they're not. Having the form break quickly and loudly avoids this problem, since people won't be able to use django-registration until they actually read the documentation and do the work to figure out what integration is necessary.
