### ISSUE TITLE
User Registration with error: no such table: auth_user

### ISSUE THREAD

**Issue by tytarenko** [ubernostrum/django-registration#73]
Why do not set model = User in class Meta in RegistrationForm?
@ubernostrum You should to add in class Meta in rRegistrationForm simple fix model = User. Registration does not work without it. Because your class Meta(UserCreationForm.Meta) in class RegistrationForm inhered parent Meta. And in django.contrib.auth.forms.UserCreationForm does not used construction like it **User = get_user_model()**. Django developers are using hard code **from django.contrib.auth.models import User**

**Comment by ubernostrum** [comment]
This is not a bug; the documentation explains what you need to do for a custom user.

**Comment by tytarenko** [comment]
I read documentation. But could me, please, explain for what need to duplicate code and re-declare explicit statement if used custom user as default in setting?

**Comment by ubernostrum** [comment]
It's left as an explicit step deliberately because there are multiple things you need to do to make a custom user model work. If the form just automatically updated to the correct model, people might not notice a problem with their setup until later on, and that would be bad; instead, they get a very loud un-ignorable error very quickly and then have to go read the documentation to make sure they do this correctly.
