### ISSUE TITLE
Should we add base templates for example?

### ISSUE THREAD

**Issue by Windsooon** [ubernostrum/django-registration#88]
Should we add base templates for example? I think that will be easier to use, maybe I can create some pull request for templates files.

**Comment by ubernostrum** [comment]
https://django-registration.readthedocs.io/en/2.2/faq.html#installation-and-setup

**Comment by unformatt** [comment]
> Any attempt to provide templates which would work with all the possibilities would probably end up working with none of them.

I just don't buy this. I've been using django-registration years and this is a hassle everytime. So I go to an old project and copy the templates over and modify them as needed - It's not easy to start from a blank file. Having just a basic example of a view with a Form and the associated template would be a great starting point. The documentation is otherwise stellar.
